#!/bin/bash
# Slurm sbatch script
# Generated by: RunRunner
# Datetime: 2025-04-24 21:30:19

#SBATCH --qos=normal
#SBATCH --mem=10000
#SBATCH --time=6:00
#SBATCH --partition=c23ms
#SBATCH --account=thes1934
#SBATCH --array=0-0%1
#SBATCH --output=Output/Log/configure_solver_2025-04-24-21.30.19/Default_Configuration:_SCIP_Validation_on_Europe_3h_single-%4a.out
#SBATCH --error=Output/Log/configure_solver_2025-04-24-21.30.19/Default_Configuration:_SCIP_Validation_on_Europe_3h_single-%4a.err
#SBATCH --dependency=

CMD=(  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 1 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
)
WORKINGDIR=(  \
	. \
)

hostnamectl
cd ${WORKINGDIR[$SLURM_ARRAY_TASK_ID]}
echo "          Job name: $SLURM_JOB_NAME"
echo "            Job ID: $SLURM_JOB_ID"
echo "     Task array ID: $SLURM_ARRAY_TASK_ID"
echo " Working directory: $(pwd)"
echo "           Command: ${CMD[$SLURM_ARRAY_TASK_ID]}"
echo "        Start time: $(date --rfc-3339=ns)"

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate sparkle

echo ----- srun start -----
srun ${CMD[$SLURM_ARRAY_TASK_ID]} 
echo ----- srun end -----
echo           End time: $(date --rfc-3339=ns)
