#!/bin/bash
# Slurm sbatch script
# Generated by: RunRunner
# Datetime: 2025-04-24 21:30:19

#SBATCH --qos=normal
#SBATCH --mem=10000
#SBATCH --time=6:00
#SBATCH --partition=c23ms
#SBATCH --account=thes1934
#SBATCH --array=0-19%25
#SBATCH --output=Output/Log/configure_solver_2025-04-24-21.30.19/SMAC2:_SCIP_on_Europe_3h_single-%4a.out
#SBATCH --error=Output/Log/configure_solver_2025-04-24-21.30.19/SMAC2:_SCIP_on_Europe_3h_single-%4a.err
#SBATCH --dependency=

CMD=(  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_2_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 2 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 2 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_3_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 3 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_4_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 4 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 4 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_5_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 5 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 5 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_6_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 6 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 6 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_7_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 7 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 7 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_8_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 8 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 8 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_9_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 9 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 9 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_10_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 10 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 10 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_11_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 11 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 11 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_12_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 12 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 12 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_13_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 13 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 13 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_14_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 14 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 14 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_15_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 15 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 15 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_16_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 16 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 16 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_17_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 17 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 17 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_18_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 18 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 18 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_19_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 19 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 19 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_20_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 20 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 20 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_21_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt 21 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/SCIP_Europe_3h_single_scenario.txt --seed 21 '  \
)
WORKINGDIR=(  \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
)
OUT=(  \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_2_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_3_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_4_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_5_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_6_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_7_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_8_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_9_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_10_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_11_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_12_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_13_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_14_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_15_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_16_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_17_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_18_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_19_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_20_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/results/SCIP_Europe_3h_single_seed_21_smac.txt \
)
hostnamectl
cd ${WORKINGDIR[$SLURM_ARRAY_TASK_ID]}
echo "          Job name: $SLURM_JOB_NAME"
echo "            Job ID: $SLURM_JOB_ID"
echo "     Task array ID: $SLURM_ARRAY_TASK_ID"
echo " Working directory: $(pwd)"
echo "           Command: ${CMD[$SLURM_ARRAY_TASK_ID]}"
echo "        Start time: $(date --rfc-3339=ns)"

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate sparkle

echo ----- srun start -----
srun ${CMD[$SLURM_ARRAY_TASK_ID]} > ${OUT[$SLURM_ARRAY_TASK_ID]}
echo ----- srun end -----
echo           End time: $(date --rfc-3339=ns)
