#!/bin/bash
# Slurm sbatch script
# Generated by: RunRunner
# Datetime: 2025-04-24 21:30:19

#SBATCH --qos=normal
#SBATCH --mem=10000
#SBATCH --time=6:00
#SBATCH --partition=c23ms
#SBATCH --account=thes1934
#SBATCH --array=0-19%20
#SBATCH --output=Output/Log/configure_solver_2025-04-24-21.30.19/SMAC2:_Validating_20_SCIP_Configurations_on_Europe_3h_single-%4a.out
#SBATCH --error=Output/Log/configure_solver_2025-04-24-21.30.19/SMAC2:_Validating_20_SCIP_Configurations_on_Europe_3h_single-%4a.err
#SBATCH --dependency=afterany:56444847

CMD=(  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 7 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 8 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 9 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 10 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 11 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 12 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 13 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 14 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 15 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 16 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 17 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 18 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 19 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 20 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_single/problem_instance_europe_jan_3h.json --run-index 21 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_single/validation   '  \
)
WORKINGDIR=(  \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
)

hostnamectl
cd ${WORKINGDIR[$SLURM_ARRAY_TASK_ID]}
echo "          Job name: $SLURM_JOB_NAME"
echo "            Job ID: $SLURM_JOB_ID"
echo "     Task array ID: $SLURM_ARRAY_TASK_ID"
echo " Working directory: $(pwd)"
echo "           Command: ${CMD[$SLURM_ARRAY_TASK_ID]}"
echo "        Start time: $(date --rfc-3339=ns)"

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate sparkle

echo ----- srun start -----
srun ${CMD[$SLURM_ARRAY_TASK_ID]} 
echo ----- srun end -----
echo           End time: $(date --rfc-3339=ns)
