#!/bin/bash
# Slurm sbatch script
# Generated by: RunRunner
# Datetime: 2025-04-22 16:04:54

#SBATCH --qos=normal
#SBATCH --mem=10000
#SBATCH --time=30:00
#SBATCH --partition=c23ms
#SBATCH --array=0-59%60
#SBATCH --output=Output/Log/configure_solver_2025-04-22-16.04.53/SMAC2:_Validating_5_SCIP_Configurations_on_Europe_3h_year-%4a.out
#SBATCH --error=Output/Log/configure_solver_2025-04-22-16.04.53/SMAC2:_Validating_5_SCIP_Configurations_on_Europe_3h_year-%4a.err
#SBATCH --dependency=afterany:56317591

CMD=(  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_aug_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_aug_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_aug_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_aug_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_aug_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_mar_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_mar_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_mar_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_mar_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_mar_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_feb_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_feb_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_feb_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_feb_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_feb_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_dec_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_dec_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_dec_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_dec_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_dec_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_may_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_may_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_may_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_may_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_may_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jun_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jun_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jun_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jun_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jun_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jan_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jan_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jan_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jan_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jan_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jul_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jul_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jul_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jul_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_jul_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_nov_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_nov_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_nov_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_nov_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_nov_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_oct_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_oct_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_oct_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_oct_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_oct_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_sep_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_sep_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_sep_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_sep_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_sep_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_apr_3h.json --run-index 2 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_apr_3h.json --run-index 3 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_apr_3h.json --run-index 4 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_apr_3h.json --run-index 5 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/solver/solver_cli.py --solver Solvers/SCIP --instance Instances/Europe_3h_year/problem_instance_europe_apr_3h.json --run-index 6 --performance-dataframe Output/Performance_Data/performance_data.csv --cutoff-time 60 --log-dir Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/validation   '  \
)
WORKINGDIR=(  \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
	. \
)

hostnamectl
cd ${WORKINGDIR[$SLURM_ARRAY_TASK_ID]}
echo "          Job name: $SLURM_JOB_NAME"
echo "            Job ID: $SLURM_JOB_ID"
echo "     Task array ID: $SLURM_ARRAY_TASK_ID"
echo " Working directory: $(pwd)"
echo "           Command: ${CMD[$SLURM_ARRAY_TASK_ID]}"
echo "        Start time: $(date --rfc-3339=ns)"

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate sparkle

echo ----- srun start -----
srun ${CMD[$SLURM_ARRAY_TASK_ID]} 
echo ----- srun end -----
echo           End time: $(date --rfc-3339=ns)
