#!/bin/bash
# Slurm sbatch script
# Generated by: RunRunner
# Datetime: 2025-04-22 16:04:54

#SBATCH --qos=normal
#SBATCH --mem=10000
#SBATCH --time=30:00
#SBATCH --partition=c23ms
#SBATCH --array=0-4%25
#SBATCH --output=Output/Log/configure_solver_2025-04-22-16.04.53/SMAC2:_SCIP_on_Europe_3h_year-%4a.out
#SBATCH --error=Output/Log/configure_solver_2025-04-22-16.04.53/SMAC2:_SCIP_on_Europe_3h_year-%4a.err
#SBATCH --dependency=

CMD=(  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_2_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt 2 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt --seed 2 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_3_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt 3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt --seed 3 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_4_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt 4 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt --seed 4 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_5_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt 5 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt --seed 5 '  \
	'python3 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/configurator/configurator_cli.py SMAC2 /rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_6_smac.txt Output/Performance_Data/performance_data.csv Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt 6 /rwthfs/rz/cluster/home/vx475510/miniforge3/envs/sparkle/lib/python3.10/site-packages/sparkle/Components/smac2-v2.10.03-master-778/smac --scenario-file Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/SCIP_Europe_3h_year_scenario.txt --seed 6 '  \
)
WORKINGDIR=(  \
	. \
	. \
	. \
	. \
	. \
)
OUT=(  \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_2_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_3_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_4_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_5_smac.txt \
	/rwthfs/rz/cluster/home/vx475510/satellite-operations-planning/sparkle/Output/Configuration/Raw_Data/SMAC2/SCIP_Europe_3h_year/results/SCIP_Europe_3h_year_seed_6_smac.txt \
)
hostnamectl
cd ${WORKINGDIR[$SLURM_ARRAY_TASK_ID]}
echo "          Job name: $SLURM_JOB_NAME"
echo "            Job ID: $SLURM_JOB_ID"
echo "     Task array ID: $SLURM_ARRAY_TASK_ID"
echo " Working directory: $(pwd)"
echo "           Command: ${CMD[$SLURM_ARRAY_TASK_ID]}"
echo "        Start time: $(date --rfc-3339=ns)"

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate sparkle

echo ----- srun start -----
srun ${CMD[$SLURM_ARRAY_TASK_ID]} > ${OUT[$SLURM_ARRAY_TASK_ID]}
echo ----- srun end -----
echo           End time: $(date --rfc-3339=ns)
